twig:
    default_path:         '%kernel.project_dir%/templates'
    debug:                '%kernel.debug%'
    strict_variables:     '%kernel.debug%'
    exception_controller: null
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - '@EWZRecaptcha/Form/ewz_recaptcha_widget.html.twig'
    globals:
        locale:                    '%locale%'
        front_web_title:           '%front_web_title%'
        front_web_phone:           '%front_web_phone%'
        front_web_address:         '%front_web_address%'
        front_web_postal_code:     '%front_web_postal_code%'
        front_web_city:            '%front_web_city%'
        front_web_province:        '%front_web_province%'
        front_legal_id_tax_number: '%front_legal_id_tax_number%'
        google_analytics_enabled:  '%google_analytics_enabled%'
        google_analytics_code:     '%google_analytics_code%'
        mailer_destination:        '%mailer_destination%'
