parameters:
    locale:                    '%env(string:DEFAULT_LOCALE)%'
    front_web_title:           '%env(string:PROJECT_WEB_TITLE)%'
    front_web_phone:           '%env(string:PROJECT_WEB_PHONE)%'
    front_web_address:         '%env(string:PROJECT_WEB_ADDRESS)%'
    front_web_postal_code:     '%env(string:PROJECT_WEB_POSTAL_CODE)%'
    front_web_city:            '%env(string:PROJECT_WEB_CITY)%'
    front_web_province:        '%env(string:PROJECT_WEB_PROVINCE)%'
    front_legal_id_tax_number: '%env(string:PROJECT_LEGAL_ID_TAX_NUMBER)%'
    google_recaptcha_site_key: '%env(string:GOOGLE_RECAPTCHA_SITE_KEY)%'
    google_analytics_enabled:  '%env(bool:GOOGLE_ANALYTICS_IS_ENABLED)%'
    google_analytics_code:     '%env(string:GOOGLE_ANALYTICS_ACCOUNT)%'
    mailer_destination:        '%env(string:MAILER_DESTINATION)%'
    delivery_dev_address:      '%env(string:DEV_DELIVERY_ADDRESS)%'

services:
    _defaults:
        autowire:      true
        autoconfigure: true
        bind:
            $adminManagerEmail: ''
            $frontProjectTitle: ''
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
